---
title: "Weight Lifting Data Analysis"
author: "Geoscientist"
date: "15 november 2015 г."
output: html_document
---
**Abstract*s*  
This paper provide complex analysis of "Weight Lifting Exercise Dataset". Analysis process consists of few stages: getting and cleaning data, exploratory data analysis, feature selecting, model training, model evaluation.  

Dataset description

**Getting and cleaning data**
```{r}
# downloading and reading data
library(caret)
download.file('https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv', destfile = 'train_data.csv')
download.file('https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv', destfile = 'test_data.csv')
train_data <- read.csv("train_data.csv", header = TRUE)
test_data <- read.csv("test_data.csv", header = TRUE)

```

```{r, echo=FALSE}
# cleaning empty features
train_data <- train_data[, c(2, 8:160)]
test_data <- test_data[, c(2, 8:160)]
not_empty_data <- apply(!is.na(train_data), 2, sum)>19621
train_data <- train_data[, not_empty_data]
test_data <- test_data[, not_empty_data]

# data preprocessing
zerovals <- nearZeroVar(train_data)
train_data <- train_data[, -zerovals]
test_data <- test_data[, -zerovals]

trControl <- trainControl(method = "cv", repeats = 5)
inTrain <- createDataPartition(train_data$classe, p = 0.6, list = FALSE)
tr_sample <- train_data[inTrain, ]
ts_sample <- train_data[-inTrain, ]
rf_model <- train(classe ~ ., tr_sample, method = "rf")
print(rf_model$finalModel)
vImport <- varImp(rf_model)
plot(vImport)

features <- as.data.frame(vImport$importance)
features$names <- rownames(features)
best_features <- subset(features, features$Overall > 5)


tr_sample1 <- tr_sample[, c(best_features$names, "classe")]
rf_model1 <- train(classe ~ ., tr_sample1, method = "rf")

rf_model$results
rf_model1$results

# as we can see model with fewer count of features not bad and we will use it.

gbm_model <- train(classe ~ ., data = tr_sample1, method = "gbm", trControl = trControl, verbose = FALSE)
gbm_model$results

svm_model <- train(classe ~ ., data = tr_sample1, method = "svmLinear", trControl = trControl)
svm_model$results

ts_sample1$predicted_sample <- predict(rf_model1, ts_sample1)
rf_cm <- confusionMatrix(ts_sample1$predicted_sample, ts_sample1$classe)
rf_cm

ts_sample1$predicted_gbm <- predict(gbm_model, ts_sample1)
gbm_cm <- confusionMatrix(ts_sample1$predicted_gbm, ts_sample1$classe)
gbm_cm

# finally we selected rf_model1
```

